//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueryStatsAnalysis.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QueryStatsAnalysis.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string ComparisonTemplate {
            get {
                return ResourceManager.GetString("ComparisonTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abs absolute access add_months adddate admin after aggregate allocate are array assertion at audit authid autonomous_transaction avg before benchmark bfilename bigint bin binary binary_checksum binary_integer bit bit_count bit_and bit_or blob body boolean both breadth call cascaded catalog ceil char_base character chartorowid checksum checksum_agg chr class clob cluster collation collect comment completion compress connect connection constant constraints constructorcreate containsable conv corr correspondin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KEYWORDS {
            get {
                return ResourceManager.GetString("KEYWORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add external procedure all fetch public alter file raiserror and fillfactor read any readtext as foreign reconfigure asc freetext references authorization freetexttable replication backup from restore begin full restrict between function return break goto revert browse grant revoke bulk group by having rollback cascade holdlock rowcount case identity rowguidcol check identity_insert rule checkpoint identitycol save close if schema clustered in securityaudit index select collate inner semantickeyphrasetable  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KEYWORDS2 {
            get {
                return ResourceManager.GetString("KEYWORDS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abs datediff power  acos day radians  asin degrees round  atan exp sign  atn2 floor sin  ceiling isnull square  coalesce isnumeric sqrt  cos log tan  cot log10 year  datalength month   dateadd nullif  @@datefirst @@options  @@dbts @@remserver  @@langid @@servername  @@language @@servicename  @@lock_timeout @@spid  @@max_connections @@textsize  @@max_precision @@version  @@nestlevel   cast convert    parse    try_cast    try_convert    try_parse    @@cursor_rows cursor_status  @@fetch_status   sysdatetime  s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KEYWORDS3 {
            get {
                return ResourceManager.GetString("KEYWORDS3", resourceCulture);
            }
        }
    }
}
